### ISSUE TITLE
Error: `schema` may not be used as a schema pathname

### ISSUE THREAD

**Issue by abettke** [vickenstein/mongoose-association#2]
Just starting playing around with this library and ran into this issue right off the bat. Tried creating a belongsTo association on a model, nothing fancy

```
const schema = new mongoose.Schema({
/// My Schema
})
	/** Associations */
	.belongsTo('MyOtherModel')
```

**Comment by abettke** [comment]
Figured it out. The above syntax won't work. This library can't build the relationship when chaining it like that, I was able to get this to work calling the function directly on the returned schema.

```
const schema = new mongoose.Schema({
/// My Schema
})

/** Associations */
schema.belongsTo('MyOtherModel')

```

**Comment by vickenstein** [comment]
Awesome, feel free to give some syntax suggestions. I would love to create more alias methods.

**Comment by abettke** [comment]
It would be nice to be able to write in the syntax of the first comment, it seems like it would flow more naturally and feel better integrated with mongoose itself. Something like below;

```
const schema = new mongoose.Schema({ ... })
   .belongsTo(...)
   .belongsTo(...)
   .hasMany(...)
```

**Comment by vickenstein** [comment]
I originally was in favor of that style, but while building out this repo i learned there was methods that I wanted to chain on the associations that was created.
```javascript
const schema = new mongoose.Schema({ ... })
schema.polymorphic(...).index(1, { unique: true })
```
where in this method the indexing is performed on the polymorphic association rather than the schema itself. a wrapper to automatically create a multi-column index using the polymorphic type / reference id.
```javascript
const schema = new mongoose.Schema({...})
   .polymorphic(...)
schema.associate(...).index(1, { unique: true }) // helper method to find the association on the schema
```
I found returning the schema itself cause the schema declaration more cumbersome, and less maintainable.
